### ISSUE TITLE
midi channels wrong

### ISSUE THREAD

**Issue by oweijers** [Tjeerdw/Miditronics_output#10]
It seems like the code is outputting a channel lower than the UI says. For example: when the module is configured to send on channel 8, the setzer receives input on channel 7.

**Comment by oweijers** [comment]
code module doorgelicht, nog geen oorzaak gevonden. Ook ChatGPT weet het niet.

To Do:
Kijken of het echt de module is door communicatie vanaf module op seriele-outputmodule te analyseren. Voor hetzelfde geld is het de Setzer..

**Comment by Tjeerdw** [comment]
Getest met hairless MIDI, die ziet de juiste kanalen, issue zit denk ik in Setzer
